### ISSUE TITLE
Front-end progress tracker

### ISSUE THREAD

**Issue by chukwuka-ezeaka** [hngi/Team-Thor#1]

**Comment by Young-Einstein10** [comment]
we will be having our conversation here pending the time we find a way to create a group on slack....only admins or workspace owners can create groups on slack, so I will advise we make our conversations here, if there is any changes everyone will be duly informed, and please remember don't push to master, always branch out

**Comment by AbdQaadir** [comment]
Okay @Young-Einstein10 , please add me to the collaborators.

**Comment by Sophi-E** [comment]
no code yet for frontend? i only see the solar tracker. what are the assigned tasks? who is doing what?

**Comment by chukwuka-ezeaka** [comment]
@AbdQaadir you've been added as a collaborator

**Comment by chukwuka-ezeaka** [comment]
Front-end devs, someone should push something, it can be just a skeletal framework of the web app, so other devs can create branches and start working

**Comment by Sophi-E** [comment]
Are we using any framework?

**Comment by Young-Einstein10** [comment]
@Sophi-E. yes any frame work can be used....just use any tool that will make us deliver today

**Comment by origho** [comment]
Nice one

**Comment by origho** [comment]
@Young-Einstein10, please make me a collaborator.

**Comment by Young-Einstein10** [comment]
@origho. @chukwuka-ezeaka. Is in charge of sending out invites pls send him a message how slack display name is @burby

**Comment by Young-Einstein10** [comment]
Have we all gotten the design we working on???......its d design @sooter sent in d group

**Comment by Sophi-E** [comment]
I haven’t. I’ll check it now

**Comment by peezykon** [comment]
Okay @Young-Einstein10 , please add me to the collaborators.

**Comment by Vimby** [comment]
Hello team , so are we only working with the homepage for now

**Comment by origho** [comment]
Alright

**Comment by devphenom** [comment]
I am working on the home page RN, and I think @AbdQaadir said he's working on the signup and login too, so someone else can work on 'about the app' section, and rest should work on the main workspace. Just a suggestion though. Let's all start working on something and we join everything together once we are all true

**Comment by Sophi-E** [comment]
I’ll work on the about page

**Comment by devphenom** [comment]
Thats good @Sophi-E

**Comment by devphenom** [comment]
I have completed the home page now

**Comment by AbdQaadir** [comment]
Great @SirPhenom, I have also committed the login and sign up page, just that it needs some fine-tuning. I hope someone continue from here, for I may have a busy day.

**Comment by AbdQaadir** [comment]
@Sophi-E , how far have you gone with the about page?

**Comment by Westernwells** [comment]
Please which design are you guys working on.

**Comment by Young-Einstein10** [comment]
I agree with @Sirphenom's idea lets all have a working and functional template on ground so that d moment our design gets in all we'll be doing is porting in d changes not from scratch

**Comment by Young-Einstein10** [comment]
Also pls lets not forget while we're pushing our work online we shouldn't merge our branches after making a pull request that's it....team leads is d only person that can merge a branch after approving all changes....pls lets be careful about this, having a separate branch makes it easy for us to recover our work in case of future errors or mistakes

**Comment by Young-Einstein10** [comment]
Also our new head for the Front-End section will be @SirPhenom he's been very hardworking, working both on d front-end and design is not easy thumbs up man ...... I'll be travelling today and wouldn't want to slow things down in any manner as my PC wouldn't be with me..pls be try working well and make things smooth for him lets remember we're delivering this project tomorrow so today is all we've got.......lets get working pple

**Comment by Young-Einstein10** [comment]
Let's also remember we can use anything be it frameworks or libraries u guys are free the main objective is to deliver this today. Google is also our friend if u at facing any issues and don't hesitate to inform ur team mates about it communication and information is key....we should also check Google and YouTube for bow e can achieve the functionality of the app lets not leave that all to d back end guys every team member should have a back up plan for d team in case things go wrong that's y we should all be ready to work in whichever aspect we find our self be it FE or BE or Digital marketing

**Comment by Sanctogiacomo** [comment]
I am really happy we all doing well...

**Comment by devolasoji** [comment]
Where can I find the design we're using? Please I need a link to the figma design, so I don't start working on a totally different thing.

**Comment by devphenom** [comment]
@devolasoji continue with your work, for now the only thing on our figma design is the background and the nav bar, you can just clone that and continue with the workarea

**Comment by devphenom** [comment]
@Westernwells no definite design RN, pls work alongside @devolasoji on the main workare, thanks

**Comment by QUASAR-22** [comment]
@SirPhenom please is there anything else i can do?

**Comment by Young-Einstein10** [comment]
Oya ooo, there's work now

**Comment by Young-Einstein10** [comment]
Our objective is to make the app functional for now we'll be working with the login and sign-up page that should be easy

**Comment by Young-Einstein10** [comment]
This is how it's going to work.out stage 2 which was a functional signup and login page should be linked with d homepage and later restyled to have similar colors with our homepage

**Comment by Soot3** [comment]
👍🏿 I can start this night.

**Comment by Young-Einstein10** [comment]
@Soot3 and @Sirphenom ur efforts are duly appreciated

**Comment by Young-Einstein10** [comment]
Also everyone pls don't forget to state in ur README.md file what function u implemented in whatever branch u pushed

**Comment by Sanctogiacomo** [comment]
I am really happy we all doing well...

**Comment by Young-Einstein10** [comment]
Main Objective: 
1. Link both the sign up and login page from our stage 2 task to the homepage in ur branch.

2. After linking the page and confirming that its fully functional re style the login page with colors similar to the homepage.

3. Re style the signup page to have similar colors with the homepage.

4. Begin building the Front-End of our main workspace according to the sketch sent above .

5. Making the workspace functional after building .

6. Remember any framework is allowed and always branch out. Also remember to state whatever functionality you are adding to ur branch before pushing.

7. Anyone coming online and sees this should pick a task and start work immediately

**Comment by QUASAR-22** [comment]
i'll do the sign up page
